# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detail.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import contact_pb2 as contact__pb2
from . import group_pb2 as group__pb2
from . import precisionlocation_pb2 as precisionlocation__pb2
from . import status_pb2 as status__pb2
from . import takv_pb2 as takv__pb2
from . import track_pb2 as track__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x0c\x64\x65tail.proto\x12\x1f\x61takmap.commoncommo.protobuf.v1\x1a\rcontact.proto\x1a\x0bgroup.proto\x1a\x17precisionlocation.proto\x1a\x0cstatus.proto\x1a\ntakv.proto\x1a\x0btrack.proto\"\x81\x03\n\x06\x44\x65tail\x12\x11\n\txmlDetail\x18\x01 \x01(\t\x12\x39\n\x07\x63ontact\x18\x02 \x01(\x0b\x32(.atakmap.commoncommo.protobuf.v1.Contact\x12\x35\n\x05group\x18\x03 \x01(\x0b\x32&.atakmap.commoncommo.protobuf.v1.Group\x12M\n\x11precisionLocation\x18\x04 \x01(\x0b\x32\x32.atakmap.commoncommo.protobuf.v1.PrecisionLocation\x12\x37\n\x06status\x18\x05 \x01(\x0b\x32'.atakmap.commoncommo.protobuf.v1.Status\x12\x33\n\x04takv\x18\x06 \x01(\x0b\x32%.atakmap.commoncommo.protobuf.v1.Takv\x12\x35\n\x05track\x18\x07 \x01(\x0b\x32&.atakmap.commoncommo.protobuf.v1.TrackB\x02H\x03\x62\x06proto3"
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "detail_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"H\003"
    _DETAIL._serialized_start = 142
    _DETAIL._serialized_end = 527
# @@protoc_insertion_point(module_scope)
