# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: takmessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import cotevent_pb2 as cotevent__pb2
from . import takcontrol_pb2 as takcontrol__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10takmessage.proto\x12\x1f\x61takmap.commoncommo.protobuf.v1\x1a\x0e\x63otevent.proto\x1a\x10takcontrol.proto"\x8a\x01\n\nTakMessage\x12?\n\ntakControl\x18\x01 \x01(\x0b\x32+.atakmap.commoncommo.protobuf.v1.TakControl\x12;\n\x08\x63otEvent\x18\x02 \x01(\x0b\x32).atakmap.commoncommo.protobuf.v1.CotEventB\x02H\x03\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "takmessage_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"H\003"
    _TAKMESSAGE._serialized_start = 88
    _TAKMESSAGE._serialized_end = 226
# @@protoc_insertion_point(module_scope)
